In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('./Data/StudentsPerformance.csv')

In [4]:
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
data.value_counts('race/ethnicity')

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [7]:
data.rename(columns={'race/ethnicity':'groups'},inplace=True)

In [66]:
data.sample(5)

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
827,female,group C,some high school,standard,none,65,69,76
486,male,group D,some college,free/reduced,none,61,47,56
119,female,group C,some college,standard,none,55,69,65
636,female,group B,high school,free/reduced,completed,67,80,81
831,female,group C,bachelor's degree,free/reduced,completed,74,86,89

In [77]:
print(data['gender'].unique())
print(data['groups'].unique())
print(data['parental level of education'].unique())
print(data['lunch'].unique())
print(data['test preparation course'].unique())

['female' 'male']
['group B' 'group C' 'group A' 'group D' 'group E']
["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
['standard' 'free/reduced']
['none' 'completed']

In [78]:
groups = data.groupby('groups')

In [79]:
print(groups)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002E8FF55AFD0>

In [80]:
type(groups)

pandas.core.groupby.generic.DataFrameGroupBy

In [82]:
for group,data in groups:
    print(group)
    print(data)

group A
     gender   groups parental level of education         lunch  \
3      male  group A          associate's degree  free/reduced
13     male  group A                some college      standard
14   female  group A             master's degree      standard
25     male  group A             master's degree  free/reduced
46   female  group A          associate's degree      standard
..      ...      ...                         ...           ...
974  female  group A                some college      standard
983  female  group A                some college      standard
985    male  group A                 high school      standard
988  female  group A            some high school  free/reduced
994    male  group A                 high school      standard

    test preparation course  math score  reading score  writing score
3                      none          47             57             44
13                completed          78             72             70
14                     none          50             53             58
25                     none          73             74             72
46                completed          55             65             62
..                      ...         ...            ...            ...
974                    none          54             63             67
983               completed          78             87             91
985                    none          57             51             54
988                    none          44             45             45
994                    none          63             63             62

[89 rows x 8 columns]
group B
     gender   groups parental level of education         lunch  \
0    female  group B           bachelor's degree      standard
2    female  group B             master's degree      standard
5    female  group B          associate's degree      standard
6    female  group B                some college      standard
7      male  group B                some college  free/reduced
..      ...      ...                         ...           ...
969  female  group B           bachelor's degree      standard
976    male  group B                some college  free/reduced
980  female  group B                 high school  free/reduced
982    male  group B            some high school      standard
991  female  group B            some high school      standard

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
2                      none          90             95             93
5                      none          71             83             78
6                 completed          88             95             92
7                      none          40             43             39
..                      ...         ...            ...            ...
969                    none          75             84             80
976               completed          60             62             60
980                    none           8             24             23
982               completed          79             85             86
991               completed          65             82             78

[190 rows x 8 columns]
group C
     gender   groups parental level of education         lunch  \
1    female  group C                some college      standard
4      male  group C                some college      standard
10     male  group C          associate's degree      standard
15   female  group C            some high school      standard
16     male  group C                 high school      standard
..      ...      ...                         ...           ...
979  female  group C          associate's degree      standard
984  female  group C            some high school      standard
986  female  group C          associate's degree      standard
996    male  group C                 high school  free/reduced
997  female  group C                 high school  free/reduced

    test preparation course  math score  reading score  writing score
1                 completed          69             90             88
4                      none          76             78             75
10                     none          58             54             52
15                     none          69             75             78
16                     none          88             89             86
..                      ...         ...            ...            ...
979                    none          91             95             94
984                    none          74             75             82
986                    none          40             59             51
996                    none          62             55             55
997               completed          59             71             65

[319 rows x 8 columns]
group D
     gender   groups parental level of education         lunch  \
8      male  group D                 high school  free/reduced
11     male  group D          associate's degree      standard
20     male  group D                 high school      standard
22     male  group D                some college      standard
24     male  group D           bachelor's degree  free/reduced
..      ...      ...                         ...           ...
989  female  group D                some college  free/reduced
992  female  group D          associate's degree  free/reduced
993  female  group D           bachelor's degree  free/reduced
998  female  group D                some college      standard
999  female  group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
8                 completed          64             64             67
11                     none          40             52             43
20                     none          66             69             63
22                     none          44             54             53
24                completed          74             71             80
..                      ...         ...            ...            ...
989               completed          67             86             83
992                    none          55             76             76
993                    none          62             72             74
998               completed          68             78             77
999                    none          77             86             86

[262 rows x 8 columns]
group E
     gender   groups parental level of education         lunch  \
32   female  group E             master's degree  free/reduced
34     male  group E                some college      standard
35     male  group E          associate's degree      standard
44   female  group E          associate's degree  free/reduced
50     male  group E                some college      standard
..      ...      ...                         ...           ...
962  female  group E          associate's degree      standard
968  female  group E          associate's degree      standard
987    male  group E            some high school      standard
990    male  group E                 high school  free/reduced
995  female  group E             master's degree      standard

    test preparation course  math score  reading score  writing score
32                     none          56             72             65
34                     none          97             87             82
35                completed          81             81             79
44                     none          50             56             54
50                     none          53             55             48
..                      ...         ...            ...            ...
962                    none         100            100            100
968                    none          68             76             67
987               completed          81             75             76
990               completed          86             81             75
995               completed          88             99             95

[140 rows x 8 columns]

In [84]:
parental = data.groupby('parental level of education')

In [85]:
for group,data in parental:
    print(group)
    print(data)

associate's degree
     gender   groups parental level of education         lunch  \
35     male  group E          associate's degree      standard
44   female  group E          associate's degree  free/reduced
51     male  group E          associate's degree  free/reduced
56   female  group E          associate's degree      standard
83     male  group E          associate's degree      standard
107    male  group E          associate's degree      standard
149    male  group E          associate's degree  free/reduced
190  female  group E          associate's degree      standard
216  female  group E          associate's degree  free/reduced
246    male  group E          associate's degree      standard
286    male  group E          associate's degree      standard
297    male  group E          associate's degree      standard
332    male  group E          associate's degree      standard
349    male  group E          associate's degree      standard
375    male  group E          associate's degree  free/reduced
479    male  group E          associate's degree      standard
503  female  group E          associate's degree      standard
532    male  group E          associate's degree      standard
533  female  group E          associate's degree      standard
554    male  group E          associate's degree      standard
691  female  group E          associate's degree  free/reduced
719    male  group E          associate's degree  free/reduced
726  female  group E          associate's degree      standard
755  female  group E          associate's degree      standard
779    male  group E          associate's degree      standard
795  female  group E          associate's degree  free/reduced
797  female  group E          associate's degree  free/reduced
802  female  group E          associate's degree      standard
868    male  group E          associate's degree  free/reduced
873    male  group E          associate's degree  free/reduced
884  female  group E          associate's degree      standard
886  female  group E          associate's degree      standard
891  female  group E          associate's degree      standard
894  female  group E          associate's degree      standard
926    male  group E          associate's degree  free/reduced
928    male  group E          associate's degree  free/reduced
955    male  group E          associate's degree      standard
962  female  group E          associate's degree      standard
968  female  group E          associate's degree      standard

    test preparation course  math score  reading score  writing score
35                completed          81             81             79
44                     none          50             56             54
51                completed          77             69             68
56                completed          82             85             86
83                     none          72             64             63
107               completed          66             63             64
149               completed         100            100             93
190                    none          66             65             69
216               completed          83             86             88
246                    none          89             76             74
286               completed          97             82             88
297               completed          71             74             68
332               completed          62             56             53
349                    none          87             74             76
375                    none          46             43             41
479                    none          76             71             67
503               completed          95             89             92
532               completed          62             61             58
533               completed          79             88             94
554                    none          53             45             40
691                    none          73             76             78
719               completed          91             73             80
726               completed          65             75             77
755                    none          84             95             92
779               completed          94             85             82
795               completed          57             68             73
797                    none          70             84             81
802                    none          87             94             95
868               completed          78             74             72
873                    none          90             90             82
884                    none          51             51             54
886               completed          93            100             95
891                    none          85             92             85
894                    none          59             62             69
926                    none          64             56             52
928               completed          46             43             44
955                    none          72             57             62
962                    none         100            100            100
968                    none          68             76             67
bachelor's degree
     gender   groups parental level of education         lunch  \
60     male  group E           bachelor's degree  free/reduced
114  female  group E           bachelor's degree      standard
206    male  group E           bachelor's degree      standard
241  female  group E           bachelor's degree      standard
293  female  group E           bachelor's degree      standard
386  female  group E           bachelor's degree      standard
458  female  group E           bachelor's degree      standard
476    male  group E           bachelor's degree      standard
538    male  group E           bachelor's degree      standard
566  female  group E           bachelor's degree  free/reduced
592    male  group E           bachelor's degree      standard
616  female  group E           bachelor's degree      standard
624  female  group E           bachelor's degree  free/reduced
700  female  group E           bachelor's degree      standard
757    male  group E           bachelor's degree  free/reduced
881  female  group E           bachelor's degree      standard
909    male  group E           bachelor's degree      standard
916    male  group E           bachelor's degree      standard

    test preparation course  math score  reading score  writing score
60                completed          79             74             72
114               completed          99            100            100
206                    none          82             62             62
241                    none          80             83             83
293                    none          65             73             75
386                    none          64             73             70
458                    none         100            100            100
476               completed          76             62             66
538               completed          85             66             71
566               completed          92            100            100
592                    none          68             68             64
616                    none          37             45             38
624                    none          61             58             62
700               completed          79             81             82
757               completed          70             68             72
881               completed          71             70             70
909               completed          70             64             70
916               completed         100            100            100
high school
     gender   groups parental level of education         lunch  \
137    male  group E                 high school      standard
156  female  group E                 high school  free/reduced
182  female  group E                 high school      standard
186    male  group E                 high school      standard
197    male  group E                 high school  free/reduced
207    male  group E                 high school      standard
214    male  group E                 high school      standard
263  female  group E                 high school      standard
277  female  group E                 high school      standard
321  female  group E                 high school      standard
415    male  group E                 high school      standard
419    male  group E                 high school  free/reduced
574  female  group E                 high school      standard
593  female  group E                 high school      standard
643  female  group E                 high school      standard
647  female  group E                 high school  free/reduced
807  female  group E                 high school  free/reduced
836    male  group E                 high school      standard
937  female  group E                 high school  free/reduced
949  female  group E                 high school  free/reduced
950    male  group E                 high school      standard
990    male  group E                 high school  free/reduced

    test preparation course  math score  reading score  writing score
137                    none          70             55             56
156               completed          66             74             78
182                    none          50             50             47
186                    none          80             76             65
197                    none          55             56             51
207               completed          81             80             76
214               completed          87             91             81
263                    none          99             93             90
277               completed          59             63             75
321                    none          75             86             79
415                    none          84             73             69
419               completed          57             56             54
574                    none          74             81             71
593                    none          74             76             73
643               completed          74             79             80
647                    none          64             62             68
807                    none          41             45             40
836                    none          73             64             57
937                    none          57             58             57
949               completed          57             75             73
950                    none          94             73             71
990               completed          86             81             75
master's degree
     gender   groups parental level of education         lunch  \
32   female  group E             master's degree  free/reduced
79   female  group E             master's degree      standard
164  female  group E             master's degree      standard
225  female  group E             master's degree  free/reduced
685  female  group E             master's degree      standard
845    male  group E             master's degree      standard
861  female  group E             master's degree  free/reduced
995  female  group E             master's degree      standard

    test preparation course  math score  reading score  writing score
32                     none          56             72             65
79                     none          62             68             68
164                    none          81             92             91
225                    none          45             56             54
685               completed          94             99            100
845                    none          90             85             84
861                    none          81             86             87
995               completed          88             99             95
some college
     gender   groups parental level of education         lunch  \
34     male  group E                some college      standard
50     male  group E                some college      standard
97   female  group E                some college      standard
124    male  group E                some college      standard
132    male  group E                some college  free/reduced
142  female  group E                some college  free/reduced
161  female  group E                some college  free/reduced
243    male  group E                some college      standard
255  female  group E                some college      standard
269  female  group E                some college  free/reduced
306    male  group E                some college      standard
351    male  group E                some college      standard
370    male  group E                some college      standard
385  female  group E                some college      standard
392    male  group E                some college      standard
411    male  group E                some college      standard
451  female  group E                some college      standard
462  female  group E                some college      standard
499    male  group E                some college      standard
517  female  group E                some college      standard
525    male  group E                some college      standard
602  female  group E                some college      standard
608  female  group E                some college      standard
638    male  group E                some college      standard
676  female  group E                some college      standard
686    male  group E                some college      standard
689    male  group E                some college  free/reduced
725    male  group E                some college      standard
734  female  group E                some college  free/reduced
751    male  group E                some college      standard
798    male  group E                some college      standard
822    male  group E                some college  free/reduced
852  female  group E                some college      standard
890  female  group E                some college      standard
915  female  group E                some college      standard

    test preparation course  math score  reading score  writing score
34                     none          97             87             82
50                     none          53             55             48
97                completed          63             72             70
124                    none          83             80             73
132               completed          87             74             70
142               completed          42             55             54
161               completed          75             88             85
243                    none          59             51             43
255                    none          62             73             70
269                    none          71             76             70
306               completed          99             87             81
351                    none          66             57             52
370                    none          84             77             71
385                    none          67             76             75
392                    none          76             67             67
411               completed          84             83             78
451                    none         100             92             97
462                    none          71             70             76
499                    none          76             71             72
517               completed          66             74             73
525                    none          68             60             59
602                    none          76             78             80
608                    none          61             64             62
638                    none          86             76             74
676               completed          73             78             76
686               completed          85             75             68
689                    none          93             90             83
725               completed          81             74             71
734                    none          53             58             57
751                    none          68             72             65
798                    none          69             60             54
822               completed          49             52             51
852                    none          87             85             93
890               completed          86             85             91
915                    none          68             70             66
some high school
     gender   groups parental level of education         lunch  \
76     male  group E            some high school      standard
171    male  group E            some high school      standard
233    male  group E            some high school      standard
289    male  group E            some high school      standard
383  female  group E            some high school  free/reduced
390    male  group E            some high school  free/reduced
545    male  group E            some high school  free/reduced
581  female  group E            some high school      standard
711  female  group E            some high school      standard
727    male  group E            some high school      standard
786  female  group E            some high school  free/reduced
793    male  group E            some high school      standard
813    male  group E            some high school      standard
853    male  group E            some high school      standard
895  female  group E            some high school  free/reduced
925    male  group E            some high school      standard
952  female  group E            some high school  free/reduced
987    male  group E            some high school      standard

    test preparation course  math score  reading score  writing score
76                     none          30             26             22
171                    none          94             88             78
233                    none          92             87             78
289               completed          77             76             77
383                    none          38             49             45
390               completed          73             67             59
545               completed          78             83             80
581                    none          77             79             80
711               completed          80             85             85
727               completed          68             51             57
786                    none          72             79             77
793               completed          89             84             77
813               completed          87             84             76
853                    none          82             67             61
895                    none          32             34             38
925               completed          74             64             60
952                    none          74             74             72
987               completed          81             75             76

# Aggregate function

In [86]:
groups.sum(numeric_only=True)

         math score  reading score  writing score
groups
group A        5485           5756           5578
group B       12056          12797          12464
group C       20564          22044          21637
group D       17649          18348          18378
group E       10335          10224           9997

In [ ]:
groups.mean(numeric_only=True)

         math score  reading score  writing score
groups
group A   61.629213      64.674157      62.674157
group B   63.452632      67.352632      65.600000
group C   64.463950      69.103448      67.827586
group D   67.362595      70.030534      70.145038
group E   73.821429      73.028571      71.407143

In [88]:
groups.median(numeric_only=True)

         math score  reading score  writing score
groups
group A        61.0           64.0           62.0
group B        63.0           67.0           67.0
group C        65.0           71.0           68.0
group D        69.0           71.0           72.0
group E        74.5           74.0           72.0

In [95]:
groups.max(numeric_only=True)

         math score  reading score  writing score
groups
group A         100            100             97
group B          97             97             96
group C          98            100            100
group D         100            100            100
group E         100            100            100

In [90]:
groups.count()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
groups,,,,,,,
group A,89,89,89,89,89,89,89
group B,190,190,190,190,190,190,190
group C,319,319,319,319,319,319,319
group D,262,262,262,262,262,262,262
group E,140,140,140,140,140,140,140

In [91]:
groups.std(numeric_only=True)

         math score  reading score  writing score
groups
group A   14.523008      15.543762      15.468278
group B   15.468191      15.177499      15.625173
group C   14.852666      13.997033      14.983378
group D   13.769386      13.895306      14.367707
group E   15.534259      14.874024      15.113906

In [ ]:
groups.get_group('group A').head()

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
25,male,group A,master's degree,free/reduced,none,73,74,72
46,female,group A,associate's degree,standard,completed,55,65,62

In [96]:
# Find that group which scored highest total in math

print(groups['math score'].sum().sort_values().tail(1))

groups
group C    20564
Name: math score, dtype: int64

In [97]:
# Find that group which scored average highest avg in wrting 

print(groups['writing score'].mean().sort_values().tail(1))

groups
group E    71.407143
Name: writing score, dtype: float64

In [100]:
print(parental['math score'].max().sort_values().tail(3))

parental level of education
bachelor's degree     100
associate's degree    100
some college          100
Name: math score, dtype: int64

In [101]:
parental['math score'].max().sort_values()

parental level of education
master's degree        94
some high school       94
high school            99
bachelor's degree     100
associate's degree    100
some college          100
Name: math score, dtype: int64

In [114]:
groups.groups

{'group A': [3, 13, 14, 25, 46, 61, 62, 72, 77, 82, 88, 112, 129, 143, 150, 151, 170, 228, 250, 296, 300, 305, 327, 356, 365, 368, 378, 379, 384, 395, 401, 402, 423, 428, 433, 442, 444, 464, 467, 468, 483, 489, 490, 506, 511, 539, 546, 571, 575, 576, 586, 589, 591, 597, 614, 623, 635, 651, 653, 688, 697, 702, 705, 731, 741, 769, 778, 805, 810, 811, 816, 820, 830, 832, 837, 851, 892, 902, 911, 936, 943, 960, 966, 972, 974, 983, 985, 988, 994], 'group B': [0, 2, 5, 6, 7, 9, 12, 17, 21, 26, 31, 39, 42, 43, 45, 65, 68, 75, 80, 81, 94, 96, 100, 103, 108, 109, 116, 121, 125, 126, 136, 146, 152, 157, 158, 160, 162, 167, 168, 176, 178, 188, 192, 198, 199, 203, 208, 209, 215, 218, 219, 221, 224, 232, 238, 247, 248, 252, 258, 274, 279, 284, 285, 287, 288, 295, 303, 308, 310, 311, 318, 329, 333, 335, 338, 342, 346, 350, 355, 360, 361, 380, 396, 398, 406, 407, 413, 424, 443, 448, 449, 459, 461, 474, 480, 484, 488, 494, 498, 501, ...], 'group C': [1, 4, 10, 15, 16, 18, 19, 23, 27, 28, 40, 41, 47, 49, 52, 54, 55, 59, 63, 67, 69, 73, 74, 85, 86, 90, 91, 92, 93, 95, 104, 105, 111, 115, 119, 120, 122, 131, 133, 135, 138, 141, 145, 147, 155, 163, 165, 166, 169, 173, 174, 175, 177, 180, 181, 184, 185, 189, 194, 196, 200, 202, 204, 211, 212, 213, 217, 222, 226, 229, 231, 234, 239, 245, 249, 256, 257, 259, 260, 261, 262, 266, 270, 271, 275, 276, 278, 290, 292, 298, 302, 304, 307, 313, 314, 315, 317, 320, 322, 323, ...], 'group D': [8, 11, 20, 22, 24, 29, 30, 33, 36, 37, 38, 48, 53, 57, 58, 64, 66, 70, 71, 78, 84, 87, 89, 98, 99, 101, 102, 106, 110, 113, 117, 118, 123, 127, 128, 130, 134, 139, 140, 144, 148, 153, 154, 159, 172, 179, 183, 187, 191, 193, 195, 201, 205, 210, 220, 223, 227, 230, 235, 236, 237, 240, 242, 244, 251, 253, 254, 264, 265, 267, 268, 272, 273, 280, 281, 282, 283, 291, 294, 299, 301, 309, 312, 316, 319, 336, 339, 343, 344, 348, 358, 359, 363, 369, 372, 373, 374, 376, 377, 388, ...], 'group E': [32, 34, 35, 44, 50, 51, 56, 60, 76, 79, 83, 97, 107, 114, 124, 132, 137, 142, 149, 156, 161, 164, 171, 182, 186, 190, 197, 206, 207, 214, 216, 225, 233, 241, 243, 246, 255, 263, 269, 277, 286, 289, 293, 297, 306, 321, 332, 349, 351, 370, 375, 383, 385, 386, 390, 392, 411, 415, 419, 451, 458, 462, 476, 479, 499, 503, 517, 525, 532, 533, 538, 545, 554, 566, 574, 581, 592, 593, 602, 608, 616, 624, 638, 643, 647, 676, 685, 686, 689, 691, 700, 711, 719, 725, 726, 727, 734, 751, 755, 757, ...]}

In [115]:
data.iloc[3]

gender                                     male
groups                                  group E
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   77
reading score                                76
writing score                                77
Name: 289, dtype: object

In [113]:
groups.ngroups

5

In [116]:
groups.size()

groups
group A     89
group B    190
group C    319
group D    262
group E    140
dtype: int64

In [118]:
groups.indices

{'group A': array([  3,  13,  14,  25,  46,  61,  62,  72,  77,  82,  88, 112, 129,
        143, 150, 151, 170, 228, 250, 296, 300, 305, 327, 356, 365, 368,
        378, 379, 384, 395, 401, 402, 423, 428, 433, 442, 444, 464, 467,
        468, 483, 489, 490, 506, 511, 539, 546, 571, 575, 576, 586, 589,
        591, 597, 614, 623, 635, 651, 653, 688, 697, 702, 705, 731, 741,
        769, 778, 805, 810, 811, 816, 820, 830, 832, 837, 851, 892, 902,
        911, 936, 943, 960, 966, 972, 974, 983, 985, 988, 994]),
 'group B': array([  0,   2,   5,   6,   7,   9,  12,  17,  21,  26,  31,  39,  42,
         43,  45,  65,  68,  75,  80,  81,  94,  96, 100, 103, 108, 109,
        116, 121, 125, 126, 136, 146, 152, 157, 158, 160, 162, 167, 168,
        176, 178, 188, 192, 198, 199, 203, 208, 209, 215, 218, 219, 221,
        224, 232, 238, 247, 248, 252, 258, 274, 279, 284, 285, 287, 288,
        295, 303, 308, 310, 311, 318, 329, 333, 335, 338, 342, 346, 350,
        355, 360, 361, 380, 396, 398, 406, 407, 413, 424, 443, 448, 449,
        459, 461, 474, 480, 484, 488, 494, 498, 501, 505, 507, 513, 514,
        519, 534, 551, 552, 558, 564, 565, 568, 570, 577, 578, 596, 609,
        621, 626, 631, 632, 636, 642, 644, 645, 648, 654, 655, 667, 675,
        681, 682, 684, 701, 704, 714, 715, 722, 724, 730, 737, 744, 749,
        759, 763, 765, 767, 770, 772, 774, 775, 776, 781, 782, 785, 787,
        790, 794, 803, 809, 815, 818, 823, 829, 833, 834, 838, 842, 843,
        855, 856, 858, 867, 870, 872, 882, 896, 897, 906, 914, 919, 923,
        944, 946, 948, 969, 976, 980, 982, 991]),
 'group C': array([  1,   4,  10,  15,  16,  18,  19,  23,  27,  28,  40,  41,  47,
         49,  52,  54,  55,  59,  63,  67,  69,  73,  74,  85,  86,  90,
         91,  92,  93,  95, 104, 105, 111, 115, 119, 120, 122, 131, 133,
        135, 138, 141, 145, 147, 155, 163, 165, 166, 169, 173, 174, 175,
        177, 180, 181, 184, 185, 189, 194, 196, 200, 202, 204, 211, 212,
        213, 217, 222, 226, 229, 231, 234, 239, 245, 249, 256, 257, 259,
        260, 261, 262, 266, 270, 271, 275, 276, 278, 290, 292, 298, 302,
        304, 307, 313, 314, 315, 317, 320, 322, 323, 324, 325, 326, 328,
        330, 331, 334, 337, 340, 341, 345, 347, 352, 353, 354, 357, 362,
        364, 366, 367, 371, 381, 382, 387, 393, 394, 397, 400, 404, 405,
        414, 416, 417, 420, 425, 426, 427, 429, 430, 431, 432, 434, 435,
        438, 440, 445, 447, 450, 452, 453, 454, 455, 460, 463, 465, 469,
        470, 471, 472, 482, 485, 487, 491, 492, 493, 496, 502, 508, 509,
        515, 521, 523, 524, 526, 527, 529, 530, 531, 535, 536, 540, 542,
        547, 548, 549, 550, 555, 556, 557, 561, 562, 572, 573, 585, 587,
        588, 590, 594, 595, 601, 605, 606, 607, 611, 612, 613, 615, 619,
        620, 622, 629, 633, 650, 656, 660, 661, 663, 665, 666, 668, 670,
        672, 673, 677, 683, 690, 692, 694, 696, 699, 707, 710, 716, 717,
        718, 720, 723, 729, 732, 735, 736, 739, 742, 743, 747, 748, 752,
        753, 754, 760, 766, 773, 777, 783, 784, 788, 789, 799, 800, 801,
        804, 808, 812, 814, 819, 824, 825, 826, 827, 831, 835, 839, 841,
        846, 848, 850, 854, 857, 859, 860, 863, 864, 866, 869, 871, 874,
        875, 877, 880, 885, 887, 901, 908, 912, 913, 917, 918, 921, 929,
        930, 933, 934, 940, 942, 945, 953, 954, 956, 959, 963, 967, 971,
        975, 977, 979, 984, 986, 996, 997]),
 'group D': array([  8,  11,  20,  22,  24,  29,  30,  33,  36,  37,  38,  48,  53,
         57,  58,  64,  66,  70,  71,  78,  84,  87,  89,  98,  99, 101,
        102, 106, 110, 113, 117, 118, 123, 127, 128, 130, 134, 139, 140,
        144, 148, 153, 154, 159, 172, 179, 183, 187, 191, 193, 195, 201,
        205, 210, 220, 223, 227, 230, 235, 236, 237, 240, 242, 244, 251,
        253, 254, 264, 265, 267, 268, 272, 273, 280, 281, 282, 283, 291,
        294, 299, 301, 309, 312, 316, 319, 336, 339, 343, 344, 348, 358,
        359, 363, 369, 372, 373, 374, 376, 377, 388, 389, 391, 399, 403,
        408, 409, 410, 412, 418, 421, 422, 436, 437, 439, 441, 446, 456,
        457, 466, 473, 475, 477, 478, 481, 486, 495, 497, 500, 504, 510,
        512, 516, 518, 520, 522, 528, 537, 541, 543, 544, 553, 559, 560,
        563, 567, 569, 579, 580, 582, 583, 584, 598, 599, 600, 603, 604,
        610, 617, 618, 625, 627, 628, 630, 634, 637, 639, 640, 641, 646,
        649, 652, 657, 658, 659, 662, 664, 669, 671, 674, 678, 679, 680,
        687, 693, 695, 698, 703, 706, 708, 709, 712, 713, 721, 728, 733,
        738, 740, 745, 746, 750, 756, 758, 761, 762, 764, 768, 771, 780,
        791, 792, 796, 806, 817, 821, 828, 840, 844, 847, 849, 862, 865,
        876, 878, 879, 883, 888, 889, 893, 898, 899, 900, 903, 904, 905,
        907, 910, 920, 922, 924, 927, 931, 932, 935, 938, 939, 941, 947,
        951, 957, 958, 961, 964, 965, 970, 973, 978, 981, 989, 992, 993,
        998, 999]),
 'group E': array([ 32,  34,  35,  44,  50,  51,  56,  60,  76,  79,  83,  97, 107,
        114, 124, 132, 137, 142, 149, 156, 161, 164, 171, 182, 186, 190,
        197, 206, 207, 214, 216, 225, 233, 241, 243, 246, 255, 263, 269,
        277, 286, 289, 293, 297, 306, 321, 332, 349, 351, 370, 375, 383,
        385, 386, 390, 392, 411, 415, 419, 451, 458, 462, 476, 479, 499,
        503, 517, 525, 532, 533, 538, 545, 554, 566, 574, 581, 592, 593,
        602, 608, 616, 624, 638, 643, 647, 676, 685, 686, 689, 691, 700,
        711, 719, 725, 726, 727, 734, 751, 755, 757, 779, 786, 793, 795,
        797, 798, 802, 807, 813, 822, 836, 845, 852, 853, 861, 868, 873,
        881, 884, 886, 890, 891, 894, 895, 909, 915, 916, 925, 926, 928,
        937, 949, 950, 952, 955, 962, 968, 987, 990, 995])}

In [120]:
# Custom Agreegation

groups.agg({
    'math score':'mean',
    'reading score':'max',
    'writing score':'sum',
})

         math score  reading score  writing score
groups
group A   61.629213            100           5578
group B   63.452632             97          12464
group C   64.463950            100          21637
group D   67.362595            100          18378
group E   73.821429            100           9997

In [122]:
groups.agg({
    'math score':['mean','min'],
    'reading score':'std',
    'writing score':['sum','max','min'],
})

        math score     reading score writing score
              mean min           std           sum  max min
groups
group A  61.629213  28     15.543762          5578   97  19
group B  63.452632   8     15.177499         12464   96  15
group C  64.463950   0     13.997033         21637  100  10
group D  67.362595  26     13.895306         18378  100  32
group E  73.821429  30     14.874024          9997  100  22