In [1]:
import pandas as pd

Creating Dataframe

In [2]:
# using lists

data_sample = [
    [50,60,47],
    [70,73,75],
    [100,400,34],
    [60,5,20]
]
data = pd.DataFrame(data_sample,columns=['Python','C++','Java'])
print(data)

   Python  C++  Java
0      50   60    47
1      70   73    75
2     100  400    34
3      60    5    20

In [2]:
# using dicts
Data_dicts = {
    'col1':['name1','name2','name3','name4','name5','name5'],
    'col2':[100,34,234,55,66,66],
    'col3':[10,3,23,5,66,66],
    'col4':[1002,342,2342,552,66,66],
    'col5':[1002,342,2342,552,66,66],
}
students = pd.DataFrame(Data_dicts)
print(students)
students.set_index('col1',inplace=True)
print(students)

    col1  col2  col3  col4  col5
0  name1   100    10  1002  1002
1  name2    34     3   342   342
2  name3   234    23  2342  2342
3  name4    55     5   552   552
4  name5    66    66    66    66
5  name5    66    66    66    66
       col2  col3  col4  col5
col1
name1   100    10  1002  1002
name2    34     3   342   342
name3   234    23  2342  2342
name4    55     5   552   552
name5    66    66    66    66
name5    66    66    66    66

In [4]:
import pandas as pd

In [3]:
# using read_CSV
weather = pd.read_csv("./Data/austin_weather.csv")
print(weather)

            Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
0     2013-12-21         74        60        45            67           49
1     2013-12-22         56        48        39            43           36
2     2013-12-23         58        45        32            31           27
3     2013-12-24         61        46        31            36           28
4     2013-12-25         58        50        41            44           40
...          ...        ...       ...       ...           ...          ...
1314  2017-07-27        103        89        75            71           67
1315  2017-07-28        105        91        76            71           64
1316  2017-07-29        107        92        77            72           64
1317  2017-07-30        106        93        79            70           68
1318  2017-07-31         99        88        77            66           61

     DewPointLowF HumidityHighPercent HumidityAvgPercent HumidityLowPercent  \
0              43                  93                 75                 57
1              28                  93                 68                 43
2              23                  76                 52                 27
3              21                  89                 56                 22
4              36                  86                 71                 56
...           ...                 ...                ...                ...
1314           61                  82                 54                 25
1315           55                  87                 54                 20
1316           55                  82                 51                 19
1317           63                  69                 48                 27
1318           54                  64                 43                 22

      ... SeaLevelPressureAvgInches SeaLevelPressureLowInches  \
0     ...                     29.68                     29.59
1     ...                     30.13                     29.87
2     ...                     30.49                     30.41
3     ...                     30.45                      30.3
4     ...                     30.33                     30.27
...   ...                       ...                       ...
1314  ...                     29.97                     29.88
1315  ...                      29.9                     29.81
1316  ...                     29.86                     29.79
1317  ...                     29.91                     29.87
1318  ...                     29.97                     29.91

     VisibilityHighMiles VisibilityAvgMiles VisibilityLowMiles WindHighMPH  \
0                     10                  7                  2          20
1                     10                 10                  5          16
2                     10                 10                 10           8
3                     10                 10                  7          12
4                     10                 10                  7          10
...                  ...                ...                ...         ...
1314                  10                 10                 10          12
1315                  10                 10                 10          14
1316                  10                 10                 10          12
1317                  10                 10                 10          13
1318                  10                 10                 10          12

     WindAvgMPH WindGustMPH PrecipitationSumInches               Events
0             4          31                   0.46  Rain , Thunderstorm
1             6          25                      0
2             3          12                      0
3             4          20                      0
4             2          16                      T
...         ...         ...                    ...                  ...
1314          5          21                      0
1315          5          20                      0
1316          4          17                      0
1317          4          20                      0
1318          4          20                      0

[1319 rows x 21 columns]

In [155]:
titanic = pd.read_csv("./Data/Titanic Dataset.csv")
print(titanic)
# titanic

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

Dataframe Attributes and methods

In [23]:
# shape
print(titanic.shape)
print(weather.shape)

(418, 12)
(1319, 21)

In [25]:
# dtypes
print(titanic.dtypes)
print()
print(weather.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Date                          object
TempHighF                      int64
TempAvgF                       int64
TempLowF                       int64
DewPointHighF                 object
DewPointAvgF                  object
DewPointLowF                  object
HumidityHighPercent           object
HumidityAvgPercent            object
HumidityLowPercent            object
SeaLevelPressureHighInches    object
SeaLevelPressureAvgInches     object
SeaLevelPressureLowInches     object
VisibilityHighMiles           object
VisibilityAvgMiles            object
VisibilityLowMiles            object
WindHighMPH                   object
WindAvgMPH                    object
WindGustMPH                   object
PrecipitationSumInches        object
Events                        object
dtype: object

In [26]:
#  index
print(titanic.index)
print(weather.index)
print(students.index)

RangeIndex(start=0, stop=418, step=1)
RangeIndex(start=0, stop=1319, step=1)
Index(['name1', 'name2', 'name3', 'name4', 'name5', 'name6'], dtype='object', name='col1')

In [27]:
#  columns
print(titanic.columns)
print(weather.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Index(['Date', 'TempHighF', 'TempAvgF', 'TempLowF', 'DewPointHighF',
       'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent',
       'HumidityAvgPercent', 'HumidityLowPercent',
       'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches',
       'SeaLevelPressureLowInches', 'VisibilityHighMiles',
       'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH',
       'WindGustMPH', 'PrecipitationSumInches', 'Events'],
      dtype='object')

In [ ]:
#  values
print(type(titanic))
print(type(titanic.values))
print(titanic.values)
print()
print(weather.values)

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
[[892 0 3 ... 7.8292 nan 'Q']
 [893 1 3 ... 7.0 nan 'S']
 [894 0 2 ... 9.6875 nan 'Q']
 ...
 [1307 0 3 ... 7.25 nan 'S']
 [1308 0 3 ... 8.05 nan 'S']
 [1309 0 3 ... 22.3583 nan 'C']]

[['2013-12-21' 74 60 ... '31' '0.46' 'Rain , Thunderstorm']
 ['2013-12-22' 56 48 ... '25' '0' ' ']
 ['2013-12-23' 58 45 ... '12' '0' ' ']
 ...
 ['2017-07-29' 107 92 ... '17' '0' ' ']
 ['2017-07-30' 106 93 ... '20' '0' ' ']
 ['2017-07-31' 99 88 ... '20' '0' ' ']]

Pandas Datagrame functions

In [31]:
# head and tail
print(titanic.head())

   PassengerId  Survived  Pclass  \
0          892         0       3
1          893         1       3
2          894         0       2
3          895         0       3
4          896         1       3

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                     Myles, Mr. Thomas Francis    male  62.0      0      0
3                              Wirz, Mr. Albert    male  27.0      0      0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1

    Ticket     Fare Cabin Embarked
0   330911   7.8292   NaN        Q
1   363272   7.0000   NaN        S
2   240276   9.6875   NaN        Q
3   315154   8.6625   NaN        S
4  3101298  12.2875   NaN        S

In [32]:
print(titanic.head(2))

   PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0  34.5      0      0  330911  7.8292   NaN        Q
1  47.0      1      0  363272  7.0000   NaN        S

In [33]:
print(titanic.tail())

     PassengerId  Survived  Pclass                          Name     Sex  \
413         1305         0       3            Spector, Mr. Woolf    male
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female
415         1307         0       3  Saether, Mr. Simon Sivertsen    male
416         1308         0       3           Ware, Mr. Frederick    male
417         1309         0       3      Peter, Master. Michael J    male

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked
413   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  39.0      0      0            PC 17758  108.9000  C105        C
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416   NaN      0      0              359309    8.0500   NaN        S
417   NaN      1      1                2668   22.3583   NaN        C

In [ ]:
print(titanic.tail(2))

     PassengerId  Survived  Pclass                      Name   Sex  Age  \
416         1308         0       3       Ware, Mr. Frederick  male  NaN
417         1309         0       3  Peter, Master. Michael J  male  NaN

     SibSp  Parch  Ticket     Fare Cabin Embarked
416      0      0  359309   8.0500   NaN        S
417      1      1    2668  22.3583   NaN        C

In [52]:
print(titanic.sample())

     PassengerId  Survived  Pclass                            Name   Sex  \
139         1031         0       3  Goodwin, Mr. Charles Frederick  male

      Age  SibSp  Parch   Ticket  Fare Cabin Embarked
139  40.0      1      6  CA 2144  46.9   NaN        S

In [53]:
print(titanic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB
None

In [54]:
print(titanic.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000
mean   1100.500000    0.363636    2.265550   30.272590    0.447368
std     120.810458    0.481622    0.841838   14.181209    0.896760
min     892.000000    0.000000    1.000000    0.170000    0.000000
25%     996.250000    0.000000    1.000000   21.000000    0.000000
50%    1100.500000    0.000000    3.000000   27.000000    0.000000
75%    1204.750000    1.000000    3.000000   39.000000    1.000000
max    1309.000000    1.000000    3.000000   76.000000    8.000000

            Parch        Fare
count  418.000000  417.000000
mean     0.392344   35.627188
std      0.981429   55.907576
min      0.000000    0.000000
25%      0.000000    7.895800
50%      0.000000   14.454200
75%      0.000000   31.500000
max      9.000000  512.329200

In [56]:
print(titanic.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
print(titanic.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
print(titanic.duplicated().sum())

0
     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [ ]:
print(students.duplicated().sum())
data = students.drop_duplicates()
print(data.duplicated().sum())

1
0

In [34]:
x = students.rename(columns={'col2':'Python','col3':'C++'},inplace=True)
print(x)
print(students)
# x = students.rename(columns={'col2':'Python','col3':'C++'},inplace=False)
# print(x)

None
       Python  C++  col4  col5
col1
name1     100   10  1002  1002
name2      34    3   342   342
name3     234   23  2342  2342
name4      55    5   552   552
name5      66   66    66    66
name5      66   66    66    66

In [ ]:
print(students.sum(axis=0)) # column

print(students.sum(axis=1)) # row

Python     555
C++        173
col4      4370
col5      4370
dtype: int64
col1
name1    2114
name2     721
name3    4941
name4    1164
name5     264
name5     264
dtype: int64

In [41]:
students.mean(axis=1)
students.mean(axis=0)

Python     92.500000
C++        28.833333
col4      728.333333
col5      728.333333
dtype: float64

In [42]:
print(students.var())

Python      5262.300000
C++          877.366667
col4      747306.266667
col5      747306.266667
dtype: float64

In [46]:
# standard deviation
print(students.std())

Python     72.541712
C++        29.620376
col4      864.468777
col5      864.468777
dtype: float64

selecting cols from dataframe

In [47]:
titanic.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S

In [48]:
titanic['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [50]:
titanic[['PassengerId','Name','Pclass']]

     PassengerId                                          Name  Pclass
0            892                              Kelly, Mr. James       3
1            893              Wilkes, Mrs. James (Ellen Needs)       3
2            894                     Myles, Mr. Thomas Francis       2
3            895                              Wirz, Mr. Albert       3
4            896  Hirvonen, Mrs. Alexander (Helga E Lindqvist)       3
..           ...                                           ...     ...
413         1305                            Spector, Mr. Woolf       3
414         1306                  Oliva y Ocana, Dona. Fermina       1
415         1307                  Saether, Mr. Simon Sivertsen       3
416         1308                           Ware, Mr. Frederick       3
417         1309                      Peter, Master. Michael J       3

[418 rows x 3 columns]

In [53]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [54]:
weather.columns

Index(['Date', 'TempHighF', 'TempAvgF', 'TempLowF', 'DewPointHighF',
       'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent',
       'HumidityAvgPercent', 'HumidityLowPercent',
       'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches',
       'SeaLevelPressureLowInches', 'VisibilityHighMiles',
       'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH',
       'WindGustMPH', 'PrecipitationSumInches', 'Events'],
      dtype='object')

In [52]:
weather[['Date','TempAvgF','Events']]

            Date  TempAvgF               Events
0     2013-12-21        60  Rain , Thunderstorm
1     2013-12-22        48
2     2013-12-23        45
3     2013-12-24        46
4     2013-12-25        50
...          ...       ...                  ...
1314  2017-07-27        89
1315  2017-07-28        91
1316  2017-07-29        92
1317  2017-07-30        93
1318  2017-07-31        88

[1319 rows x 3 columns]

iloc - searches using index positions
loc - searches using index labels

In [58]:
# accessing single row
titanic.iloc[5]

PassengerId                           897
Survived                                0
Pclass                                  3
Name           Svensson, Mr. Johan Cervin
Sex                                  male
Age                                  14.0
SibSp                                   0
Parch                                   0
Ticket                               7538
Fare                                9.225
Cabin                                 NaN
Embarked                                S
Name: 5, dtype: object

In [59]:
# accessing mulltiple row together
titanic.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [60]:
titanic.iloc[[0,3,5,56,44,33,232]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
56,948,0,3,"Cor, Mr. Bartol",male,35.0,0,0,349230,7.8958,NaN,S
44,936,1,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.0,1,0,11753,52.5542,D19,S
33,925,1,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
232,1124,0,3,"Wiklund, Mr. Karl Johan",male,21.0,1,0,3101266,6.4958,NaN,S

In [61]:
students

       Python  C++  col4  col5
col1
name1     100   10  1002  1002
name2      34    3   342   342
name3     234   23  2342  2342
name4      55    5   552   552
name5      66   66    66    66
name5      66   66    66    66

In [62]:
students.loc['name1']

Python     100
C++         10
col4      1002
col5      1002
Name: name1, dtype: int64

In [68]:
students.loc[['name1','name2','name5']]

       Python  C++  col4  col5
col1
name1     100   10  1002  1002
name2      34    3   342   342
name5      66   66    66    66
name5      66   66    66    66

In [ ]:
students.loc['name1':'name4':2]

Selecting both row and columns

In [ ]:
titanic.iloc[0:3,0:7] # rows,columns

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp
0,892,0,3,"Kelly, Mr. James",male,34.5,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0

In [71]:
titanic.loc[0:9:2,'PassengerId':'Pclass']

   PassengerId  Survived  Pclass
0          892         0       3
2          894         0       2
4          896         1       3
6          898         1       3
8          900         1       3

In [ ]:
# Create new columns in data frame
titanic['Country'] = 'India'
titanic.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Country
297,1189,0,3,"Samaan, Mr. Hanna",male,NaN,2,0,2662,21.6792,NaN,C,India
134,1026,0,3,"Dintcheff, Mr. Valtcho",male,43.0,0,0,349226,7.8958,NaN,S,India
289,1181,0,3,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,NaN,S,India
98,990,1,3,"Braf, Miss. Elin Ester Maria",female,20.0,0,0,347471,7.8542,NaN,S,India
187,1079,0,3,"Davies, Mr. Joseph",male,17.0,2,0,A/4 48873,8.0500,NaN,S,India
311,1203,0,3,"Vartanian, Mr. David",male,22.0,0,0,2658,7.2250,NaN,C,India
362,1254,1,2,"Ware, Mrs. John James (Florence Louise Long)",female,31.0,0,0,CA 31352,21.0000,NaN,S,India
90,982,1,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1,0,347072,13.9000,NaN,S,India
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S,India
77,969,1,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.0,2,0,11770,25.7000,C101,S,India

In [157]:
titanic['First Name'] = titanic['Name'].str.split(' ').apply(lambda x:x[0])
titanic.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Country,First Name
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.050,NaN,S,India,"Ware,"
336,1228,0,2,"de Brito, Mr. Jose Joaquim",male,32.0,0,0,244360,13.000,NaN,S,India,de
214,1106,1,3,"Andersson, Miss. Ida Augusta Margareta",female,38.0,4,2,347091,7.775,NaN,S,India,"Andersson,"
251,1143,0,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,0,SOTON/O2 3101284,7.925,NaN,S,India,"Abrahamsson,"
346,1238,0,2,"Botsford, Mr. William Hull",male,26.0,0,0,237670,13.000,NaN,S,India,"Botsford,"
124,1016,0,3,"Kennedy, Mr. John",male,NaN,0,0,368783,7.750,NaN,Q,India,"Kennedy,"
99,991,0,3,"Nancarrow, Mr. William Henry",male,33.0,0,0,A./5. 3338,8.050,NaN,S,India,"Nancarrow,"
155,1047,0,3,"Duquemin, Mr. Joseph",male,24.0,0,0,S.O./P.P. 752,7.550,NaN,S,India,"Duquemin,"
410,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.750,NaN,Q,India,"Naughton,"
313,1205,1,3,"Carr, Miss. Jeannie",female,37.0,0,0,368364,7.750,NaN,Q,India,"Carr,"

In [163]:
x = ["how","are","you"]

y=" ".join(x)
print(y)

how are you

In [167]:
name = input()
print(" ".join(name.split(" ")[:-1]))

sneha raj

astype()

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
 12  Country      418 non-null    object
 13  First Name   418 non-null    object
dtypes: float64(2), int64(5), object(7)
memory usage: 45.8+ KB

In [171]:
titanic['PassengerId'] = titanic['PassengerId'].astype('int32')

In [172]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int32
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
 12  Country      418 non-null    object
 13  First Name   418 non-null    object
dtypes: float64(2), int32(1), int64(4), object(7)
memory usage: 44.2+ KB

In [6]:
weather.columns

Index(['Date', 'TempHighF', 'TempAvgF', 'TempLowF', 'DewPointHighF',
       'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent',
       'HumidityAvgPercent', 'HumidityLowPercent',
       'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches',
       'SeaLevelPressureLowInches', 'VisibilityHighMiles',
       'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH',
       'WindGustMPH', 'PrecipitationSumInches', 'Events'],
      dtype='object')

In [8]:
print(weather.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   object
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      1319 non-null   object
dtypes: int64(3), object(18)
memory usage: 216.5+ KB
None

In [9]:
weather['Events'] = weather['Events'].astype('category')
titanic['First name'] = titanic['Sex'].astype('category')

In [10]:
print(weather.info())
print(titanic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   object
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      1319 non-null   category
dtypes: category(1), int64(3), object(17)
memory usage: 207.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
 12  First name   418 non-null    category
dtypes: category(1), float64(2), int64(5), object(5)
memory usage: 39.8+ KB
None

Value_count()

In [11]:
students

       col2  col3  col4  col5
col1
name1   100    10  1002  1002
name2    34     3   342   342
name3   234    23  2342  2342
name4    55     5   552   552
name5    66    66    66    66
name5    66    66    66    66

In [12]:
students.value_counts() # counting no. of rows

col2  col3  col4  col5
66    66    66    66      2
34    3     342   342     1
55    5     552   552     1
100   10    1002  1002    1
234   23    2342  2342    1
Name: count, dtype: int64

In [13]:
# 
students['col2'].value_counts()

col2
66     2
100    1
34     1
234    1
55     1
Name: count, dtype: int64

In [15]:
titanic['Pclass'].unique()

array([3, 2, 1])

In [14]:
# find how many passenger are there in each line
titanic['Pclass'].value_counts()

Pclass
3    218
1    107
2     93
Name: count, dtype: int64

In [30]:
weather['Events'].value_counts()

Events
                             903
Rain                         192
Rain , Thunderstorm          137
Fog , Rain , Thunderstorm     33
Fog                           21
Thunderstorm                  17
Fog , Rain                    14
Fog , Thunderstorm             1
Rain , Snow                    1
Name: count, dtype: int64

In [31]:
# count of passenger which are males and age is above 40
((titanic["Age"] >= 40) & (titanic["Sex"]=='male')).value_counts()

False    366
True      52
Name: count, dtype: int64

In [34]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First name
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,male
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,female
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,male
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,male
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,male
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,female
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,male
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,male
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,male

In [35]:
((titanic['SibSp']==0)&(titanic['Parch']==0)).value_counts()

True     253
False    165
Name: count, dtype: int64

In [92]:
(((titanic['Sex']=='male')&(titanic['Age']>50))|((titanic['Sex']=='female')&(titanic['Age']>=40))).value_counts()

False    372
True      46
Name: count, dtype: int64

sort_values()

In [93]:
titanic.sort_values('PassengerId',ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First name
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,male
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,male
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,male
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,female
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,female
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,male
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,male
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,female
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,male

In [94]:
titanic.sort_values('PassengerId')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First name
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,male
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,female
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,male
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,male
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,male
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,female
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,male
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,male
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,male

In [96]:
titanic.sort_values(['Pclass','Name'],ascending=[True,False])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First name
371,1263,1,1,"Wilson, Miss. Helen Alice",female,31.0,0,0,16966,134.5000,E39 E41,C,female
23,915,0,1,"Williams, Mr. Richard Norris II",male,21.0,0,1,PC 17597,61.3792,NaN,C,male
231,1123,1,1,"Willard, Miss. Constance",female,21.0,0,0,113795,26.5500,NaN,S,female
218,1110,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.0,1,1,113503,211.5000,C80,C,female
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C,female
251,1143,0,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,0,SOTON/O2 3101284,7.9250,NaN,S,male
57,949,0,3,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,0,348122,7.6500,F G63,S,male
345,1237,1,3,"Abelseth, Miss. Karen Marie",female,16.0,0,0,348125,7.6500,NaN,S,female
392,1284,0,3,"Abbott, Master. Eugene Joseph",male,13.0,0,2,C.A. 2673,20.2500,NaN,S,male

set_index()

In [115]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [116]:
titanic.set_index('PassengerId',inplace=True)

In [117]:
titanic

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [118]:
titanic.reset_index(inplace=True)

In [119]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [121]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks)
marks_series

maths       67
english     57
science     89
hindi      100
dtype: int64

In [127]:
# marks_series = marks_series.reset_index(inplace=True)

In [158]:
titanic['Age'] = titanic['Age'].fillna('----')

In [159]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,----,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,----,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,----,1,1,2668,22.3583,NaN,C